inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'

Style/GlobalVars:
  Exclude:
    - 'ext/liquid_c/extconf.rb'
